language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt install libgtest-dev build-essential cmake
- sudo apt-get install cmake
- sudo cmake /usr/src/googletest
- sudo cmake --build /usr/src/googletest --target install
- cd -
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  on:
    all_branches: true
  provider: script
  skip_cleanup: true
  script:
  - curl -T *.deb -ukyarovyi:$BINTRAY_API_KEY "https://api.bintray.com/content/kyarovyi/OTUS/Otus_Homework/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"